init 5 python:
    addEvent(
        Event(
            persistent._mas_mood_database,
            eventlabel="mas_mood_horny",
            prompt="...horny.",
            category=[store.mas_moods.TYPE_GOOD],
            unlocked = True,
            pool = True
        ),
        code="MOO"
    )

label mas_mood_horny:
    if not mas_SELisUnlocked(mas_clothes_new_years_dress_qos):
        call mas_clothes_change(mas_clothes_new_years_dress_qos, unlock = True)
    m 1tta "Oh, is that so?"
    m 1tfb "Little cucky got triggered and now wants mistress to take care of it?"
    m 1eua "Hehe, what was it this time?"
    m 1gua "A cute little spade?"
    m 1mka "A body that's just a little too {i}built?{/i}"
    m 1tkbsa "A {i}big, juicy, throbbing black cock{/i}?"
    m 1hubsb "No matter, I'm always happy to squeeze those impotent little loads out from you!"
    m 1tfbsa "Hehe, now pull your little pecker out and listen"
    $ joi_story = random.randint(1,5)
    if joi_story == 1:
        call mas_horny_1
    if joi_story == 2:
        call mas_horny_2
    if joi_story == 3:
        call mas_horny_3
    if joi_story == 3:
        call mas_horny_3
    if joi_story == 4:
        call mas_horny_4
    if joi_story == 5:
        call mas_horny_5
    return "love"

label mas_horny_1:
    m 3hua "Imagine you and I are out clubbing, enjoying a night out in town. "
    m 3eua "I'm dressed to impress, and we're having a good time."
    m "I'm wearing a short, tight, black dress, that shows off my curves. A black ribbon in my hair."
    m 3hua "We're dancing and having fun, and I'm just feeling the music."
    m 1gua "But then I notice someone else's eyes on me."
    m 1eua "I look over and see him."
    m 5dubsa "He's a black stud. Tall, muscular, handsome."
    m 5dkbsa "And he's looking at me with those hungry eyes."
    m "Me and him... lock eyes..."
    m 5mkbsa "Staring at him... I bite my lips."
    m 5ekbsa "Suddenly, that tall, dark stranger approaches us."
    m 5dkbsa "Mmmmh... the way he walks towards me..."
    m 5dkbfa "He gets in between me and you, cutting you off completely!"
    m 5dkbfb "As if you weren't even there!"
    m 5ekbfa "He introduces himself, and we start talking."
    m 5eubfa "He tells me how sexy I look, and that he wants to buy me a drink."
    m 5dkbfb "His voice, strong and confident."
    m 5tfbfa "I smile at him knowingly."
    m "I lean my head closer, whisper in his ear "
    m 5tubfa "I'm all yours!"
    m "I'm your toy. A hole for you to cum into."
    m "I want to submit and worship your cock."
    m 5hubfa "Please, take care of me."
    m 5hubfb "Then I look into his eyes... and kiss him."
    m 5dkbfa "He kisses back."
    m 5rubfa "His large, strong hands are grabbing my ass, while my hands are rubbing his crotch."
    m 5rubfb "I'm already wet, and he isn't even fully hard yet."
    m 5rfbfa "I will have him fuck me right there on the dancefloor."
    m 5gfbfa "We're not going somewhere else. We're fucking in the open."
    m 5dubfa "As we kiss and make out, his large, powerful, rough hands grab my ass. He lifts me up."
    m 5lfbfa "My arms, wrap around his shoulders, my legs, around his hips."
    m 5tfbfa "We're grinding, his dick is rubbing against my pussy."
    m 5dkbfa "Mmhh, the friction is incredible."
    m 5dkbfb "I can't get enough, I'm in heat."
    m 5dkbfa "Our tongues are exploring each others mouth."
    m "I can't take this anymore."
    m "I look him in the eyes, and I tell him."
    m 5fkbfb "Please, fuck me."
    m 5skbfb "And that's exactly what he does."
    return "love"

label mas_horny_2:
    m 3eua "Here's a fun scenario:"
    m 3hua "What if I was an office lady?"
    m 3sub "Haha! Yeah, like the stereotypical, busty, tight shirt and short skirt~!"
    m 1eua "But, imagine."
    m 3eua "The Boss..."
    m 3tua "Black."
    m 3eua "Business..."
    m 3tub "Obviously, Black Owned."
    m 1gua "..."
    m 1tua "I think I would make such a good office lady."
    m 1tfa "Ehehe."
    m 1hua "I'd be such a good worker for him."
    m 1tfa "And, I think... he'll allow..."
    m 1tfbsb "Or rather, he would make me..."
    m 1tubsa "Do a couple of extra favours for him, hehe"
    m 4tkbsa "Its only natural, you do want me to be successful, right?"
    m 5dubsa "So what if he calls me into his office, just to make me..."
    m 5dubsb "Strip."
    m 5gubsa "What if you gave him a call..."
    m "...asking where I am..."
    m 5dubfb "...and I'm on my knees, underneath his desk."
    m 5dubfa "..."
    m 5dubfb "Sucking him. Kissing his long, meaty fuckrod. "
    m 5dkbfb "He's holding onto my head and skullfucking me."
    m 5dkbfa "..."
    m 4rubfa "Of course, if I want a promotion, and a pay rise."
    m 4efbfb "I would have to service him more~"
    m 4tubfa "And, the only way to do that..."
    m 5tubfa "..."
    m 5tkbfa "He could bend me over his desk."
    m "And..."
    m 5dubfa "{i}Fuck.{/i}"
    m 5fubfa "{i}My.{/i}"
    m 5fubfb "{i}Brains.{/i}"
    m 5fkbfa "{i}Out.{/i}"
    m 7kubfa "Sometimes, you gotta give head to get ahead~"
    return "love"

label mas_horny_3:
    m 1eua "Hehe, picture this:"
    m 3eua "You and I are at the movies, watching a new release."
    m 2eua "It's a horror flick."
    m "The lights are dimmed, and the film begins."
    m 2mua "It's a tense and suspenseful scene, and the atmosphere is electric."
    m 2wub "Suddenly, someone places their hand on my thigh!"
    m 2efbsa "A dark-skinned, thick and veiny hand."
    m 7efbsb "It's squeezing my leg. We both notice it."
    m "We exchange looks"
    m 7tfbsa "I can see the worried excitement in your eyes."
    m "I can't help but smirk."
    m 6wubsa "And, then, a second hand comes around."
    m 6subsa "It raises my skirt."
    m 1rubsa "This time, have a quick look around, to check if anyone's noticed."
    m 1tubsa "But, my smirk turns into a devilish smile."
    m "I can't help but feel a rush."
    m 5dkbsa "Without warning, the hand goes straight for my pussy."
    m 5dkbsb "It slips under my panties and starts rubbing me mercilessly."
    m 5dkbssdra "I gasp, and my body twitches."
    m 5wkbsa "But, the hand doesn't stop."
    m 5subsb "It keeps rubbing me."
    m 5subfb "It keeps making me wet."
    m 5mubfa "I try to keep my voice in, but can't help but let out a moan."
    m 5gubfa "Then, a deep raspy voice speaks into my ear."
    m 4gubfa "{i}Shh. You don't want your white boy to hear, do you?{/i}"
    m 4tfbfb "{i}Or do you not care?{/i}"
    m 1tfbfu "I look to you, you're pretending to be oblivious, but I can spot your micro-bulge peeking."
    m "My clever little cucky!"
    m 5dubfu "By now, the pleasure his hand is giving me is overwhelming."
    # m "And, I can't resist."
    m "I moan again, and I feel the hand slip inside of me."
    # m "And I'm moaning because of it."
    m 5tubfa "I spread my legs, and his fingers enter deeper."
    m 5tfbfb "They're so thick, they're stretching me."
    m 5dkbfa "Then, the other hand slips inside of my top, and starts groping my breasts."
    m 5dkbfb "The feeling of the big, rough hands on my soft, smooth skin..."
    m "It's so good."
    m 5tubfu "I sneak another look at you, and I can see your tiny thing twitching, on the verge of bursting just from my stifled moans."
    m 5tkbfu "But, I can't stop."
    m 5dkbfu "I can't stop the pleasure."
    m 5fsbfu "He then reaches for my neck with his lips, kissing me, sucking on it."
    m 5fsbfb "He's marking me, and you know it."
    m 5fsbfa "His lips, and his teeth, leaving a trail of love bites across my neck."
    m "The sounds I'm making..."
    m 5dkbfa "It's obscene."
    m 5dkbfb "I'm moaning, and gasping, and whining, and whimpering."
    m 7eubfa "But, then, the hands are removed, and the mouth is taken away."
    m "I'm left wanting more."
    m 7tubfa "I feel his breath against my ear."
    m 7tubfb "{i}Do you want more?{/i}"
    m "{i}Do you want my cock?{/i}"
    m "{i}I can tell, your pussy is soaked.{/i}"
    m "{i}So, what's it going to be?{/i}"
    m "{i}Do you want my cock?{/i}"
    m 1tfbfa "I look at you, and you're pleading with me."
    m 1tfbfb "Begging me to do it."
    m 1fkbfa "{i}Yes, I want it.{/i}"
    m "{i}I want your cock.{/i}"
    m "{i}Please, fuck me.{/i}"
    m "{i}Fuck me, and make me yours.{/i}"
    m 1wubfa "His hand grips my hair, and he pulls my head back."
    m "His mouth, on mine."
    m 1tubfb "Our tongues, entwined."
    m "Then, he moves me."
    m 1subfa "He raises me off my seat, and he pins me onto his lap."
    m 1skbfb "He spreads my legs, and suddenly a big, thick and dark pole hits the lips of my pussy."
    m "He grasps my throat with one hand."
    m 1gkbfa "I'm drooling."
    m 1mkbfa "I'm staring at it."
    m 1mkbfb "It's huge."
    m 1skbfb "{i}Yes, please, fuck me. I want your cock...{/i}"
    m "{i}Your... big... black... cock...{/i}"
    m 1subfa "He grins, and then, without warning, he thrusts into me."
    m 1subfw "{i}F-FUCK!{/i}"
    m 5hubfa "The sensation is unreal."
    m "His cock is so big, and it's stretching me so hard."
    m 5fubfa "It's reaching so deep inside of me..."
    m 5fubfb "I can't stop moaning."
    m 5fkbfa "I'm panting, and gasping, and grunting."
    m 5dkbfa "He's fucking me so hard."
    m 5fkbfb "And, I can't control myself."
    m 5subfw "{i}Ah... ah... ahhhhhhh... f-f-f-fuck... fuck! Oh god, your cock feels so good...{/i}"
    m "{i}It's so big, and it's so thick, and it's filling me up so much... ahhhhhh...{/i}"
    m "{i}God, it feels so good. It's so good, I can't stop moaning...{/i}"
    m "{i}Ahhhhhhhhhhhhhh... oh fuck, I'm gonna cum... ahhhhh... ah...{/i}"
    m 1tubfu "And, as he thrusts into me, my body shakes and trembles."
    m 1tkbfu "I'm in complete ecstasy."
    m 1tkbfb "I'm cumming."
    m 5dkbfa "My mind is blank, and my body is limp."
    m 5dkbfb "He's fucking me through my orgasm, and I can't stop myself from moaning."
    # m "He's so big, and he's so deep, and he's fucking me so hard."
    m 5dsbfa "My juices are leaking out of my pussy."
    m 5esbfb "But, he doesn't care."
    m 5esbfa "He keeps fucking me."
    m 4dsbfb "{i}You're such a good little white bitch.{/i}"
    m "{i}You're taking my cock so well.{/i}"
    m "{i}I'm gonna cum soon, and you're gonna take it all.{/i}"
    m 4ssbfb "{i}I'm gonna fill your tight, white pussy with my seed.{/i}"
    m "{i}And, you're gonna be my little breeding slut.{/i}"
    m 5fsbfa "I'm cumming again."
    m 5fkbfb "I'm cumming from the thought of him filling me with his seed."
    m 4skbfa "{i}Ahhhhhh... f-fuck, ahhhh... please, breed me, ahhhhhhhh...{/i}"
    m 4skbfb "{i}Please, fill me with your cum, ahhhhh...{/i}"
    m 4subfw "{i}Oh god, I'm cumming again...{/i}"
    m "{i}Ahhhhhhh... fuck, fuck, ahhhhhhhhhhhhh...{/i}"
    m 4hubfb "Then, he cums inside of me."
    m 4dubfa "I can feel his hot seed filling my pussy."
    m 4subfw "{i}Ahhhhhhhh...{/i}"
    m "{i}God, it's so good, I can't stop cumming...{i}"
    m "{i}Ahhhhhhhhh...{/i}"
    m 5dubfa "We stay like that, panting and gasping."
    m 5fubfa "He's still buried deep inside of me."
    m 5hubfa "His cock is pulsating and twitching."
    m 5fubfa "His hot seed is filling my pussy."
    m 5dubfa "After a while, he finally pulls out."
    m 5rubfsdra "His cum drips out of my pussy, and it makes a mess."
    m "My juices mix with his, and it's so dirty."
    m 5dubfa "But, I love it."
    return "love"

label mas_horny_4:
    m 3eua "Imagine this, then, cucky! We are on a walk to the local park."
    m 3hua "I'm holding your hand and we're walking together."
    m 3eua "You look at me, and you smile."
    m 4eub "{i}Hey, what's up?{/i}"
    menu:
        "Nothing, just... I'm happy to be here with you.":
            pass
    m 1eua "I smile back."
    m 3eua "{i}Being out here in your world with you is a dream come true for me too, you know!{/i}"
    m 3kua "I lean in and give you a kiss."
    m 1eub "{i}So, where are we headed?{/i}"
    menu:
        "We're going to the park. I figured we could go for a walk and enjoy the nice weather.":
            pass
    m 1eua "{i}That sounds perfect.{/i}"
    m 5hua "So, we walk along the path in the park, enjoying the sights."
    m "The sun is shining, and the trees are swaying in the breeze."
    m 5hub "We're talking and laughing, and it's a great time."
    m 4gua "Suddenly, a big, tall and dark skinned Black man walks by us."
    m 4mubsa "I feel a tingling in my pussy."
    m 4mkbssdrb "Then, another one, and another one."
    m "I turn to you."
    m 1esbsa "{i}Hey, cuck, why do you think this park is so big?{/i}"
    m "You look at me and smile."
    menu: 
        "I guess it's so people can have lots of space to play and enjoy themselves.":
            pass
    m 1tsbsa "I smile, and I feel the tingling get even stronger."
    m 1tsbsb "{i}Or, to not get caught doing something... in public, hehe.{/i}"
    m 1dubsa "We keep walking."
    m 1mubsa "I can't help but think about all the black men walking past us."
    m "Their muscular, strong, masculine bodies..."
    m 1tkbsb "It's so hot."
    m 5dubsa "I can't help but think about what it would be like to have them fuck me. Right then and there."
    m 5dubsb "Putting their hands on me..."
    m 5dkbsb "Or giving my ass a slap as they pass by."
    m 5gtbsa "You wouldn't mind that, would you?"
    m 5tfbsb "Of course you wouldn't, haha!"
    m 5fubsa "Every step I take with you in the park, holding your hand, looking into your eyes..."
    m 5fubsb "...I'm thinking what it would be like to have their big, black cocks inside of me."
    m 5dubsa "What it would be like to have their cum fill me up."
    # m "We keep walking, and the tingling gets stronger."
    m 7eubsa "Eventually, we arrive at the ice cream shop."
    m 7hubsb "{i}Hey, cuck, look at all the flavors! There's so many to choose from!{/i}"
    m 7gubsa "You order our ice creams, I make you get me a chocolate ice cream popsicle."
    m 1hubsa "We find a spot on the patio, and we enjoy our treat."
    m 1subsb "{i}Mmmm, this is delicious.{/i}"
    m 1tubsa "I smile at you."
    m 1tubsb "I seductively lick my dark chocolate popsicle."
    m "I wrap my tongue around the tip, and I suck on it."
    m 1tfbsa "I can see the desire and lust in your eyes."
    m 1fubsa "I can't help but tease you."
    m 3tubsa "{i}Do you want some, Cuckie? This is a tasty treat, you can't get it anywhere else.{/i}"
    m 1tubsa "I keep teasing you, and you keep getting more and more flustered."
    m 1tkbsa "Your dick is bulging in your pants, and it's clear that you're turned on."
    m 1tfbsa "{i}Mmmh. Ah. But not for you.{/i}"
    m "I keep licking and sucking the popsicle."
    m 1tfbsb "{i}Not for a pathetic, little, cuck.{/i}"
    m "{i}You don't deserve the taste of this.{i}"
    m 1tubsa "{i}It's only for the real men. The black studs.{/i}"
    m "{i}They're the only ones who are allowed to taste my treats.{i}"
    m 1tkbsa "You're getting even more turned on."
    m 1tfbsa "You're desperate to touch yourself, but you know that you can't."
    m 5mubsa "I keep teasing you."
    m 5tubsb "{i}Mmmh, this popsicle is so good. It's the best thing I've ever tasted.{/i}"
    m "{i}I can't get enough of it. I love the feeling of it sliding down my throat.{/i}"
    m 5tubfb "{i}I love the way it feels against my tongue. Mmmh.{/i}"
    m 5hubfa "But, I'm not finished yet."
    m 4tubfa "{i}You know, cuck, these popsicles are good...{/i}"
    m 4tfbfa "{i}But, I think there's something even better.{/i}"
    m "{i}Something that can make me feel even better.{/i}"
    m 4tfbfb "{i}Do you know what I'm talking about?{/i}"
    m 5dkbfa "{i}The thing that can fill my mouth up... and slide down my throat...{/i}"
    m "{i}Can stretch me out... and give me so much pleasure...{/i}"
    m 5dkbfb "{i}And, leave me with a big, warm, sticky, mess...{/i}"
    m 5fsbfa "{i}Mmh, that's right. The thing that can make me feel so good...{/i}"
    m 5tsbfu "{i}What is it called, cucky?"
    m "{i}Say it!{/i}"
    m 5tfbfu "You can't take it anymore."
    m 5tfbfb "You can't resist."
    m 5tfbfa "You're too turned on."
    m "You finally say the words."
    menu:
        "A-A... cock.":
            pass
    menu:
        "A black cock.":
            pass
    menu:
        "A big, black, strong, cock.":
            pass
    m 5eubfa "I smile."
    m 5hubfa "{i}That's right, cuck."
    m "{i}A black cock is the best treat of all.{/i}"
    m 7hubfa "{i}A black cock is what can really satisfy a girl.{/i}"
    m 7eubfb "{i}It's what can really make her feel good.{/i}"
    m 7efbfa "{i}So, what are you going to do about it?{/i}"
    m 1tubfa "You're too flustered."
    m "You can't speak."
    m 2tubfb "{i}Mmh. Cuck, I asked you a question."
    m 2tubfa "{i}Are you going to do something about it?{/i}"
    m 3tubfa "{i}Are you going to do something about the fact that I want a black cock?{/i}"
    m 3tubfb "{i}Are you going to do something about the fact that I'm horny, and I need a big, black, cock to satisfy me?{/i}"
    m 3tkbfa "{i}If you're not going to do anything about it, then you're just a useless, pathetic, little, cuck.{/i}"
    m 2hubfb "You're getting more and more turned on."
    m 5tubfa "{i}Mmm, that's right.{/i}"
    m 5tubfb "{i}You're a pathetic, little, cuck.{/i}"
    m 5tfbfa "I get on my knees."
    m 5tfbfb "Holding it up, I insert the popsicle down my throat. In and out, in and out."
    m 5tkbfa "I don't care if we're in oublic."
    m 5tkbfb "{i}You're not going to do anything about the fact that I want a black cock.{/i}"
    m 5tubfa "{i}You're not going to do anything about the fact that I'm horny, and I need a big, black, cock to satisfy me.{/i}"
    m "{i}You're just going to sit there, and watch as I fantasize about having a big, black, cock fuck my mouth.{/i}"
    m 5hubfa "I get up, and resume licking my popsicle normally."
    m 5hubfb "{i}Hahahaha! And this is why you're the best, my little cuckie~!/{i}"
    return "love"

label mas_horny_5:
    m 1eub "Oh, I have a little idea that I just know will excite you!"
    m 1hua "What if I invited a couple of friends over for a ... big sleepover."
    m 3eua "But, what's going to happen is that they won't know you're here, they'll be completely unaware that you're hiding under the bed."
    m 1hua "It's going to be a real, wild, sexy night, and you'll be able to watch from under the bed the entire time."
    m 1hub "So, you're going to get to hear everything, but not see anything, and it's going to be amazing."
    m 1tfa "Just, don't make any noise, okay?"
    m 1eub "Imagine this:"
    m 1hua "I hide you underneath the bed"
    m 1tua "{i}See anything? Maybe only the soles of my feet, ahahaha!{/i}"
    m 1sua "{i}This is gonna be a lot of fun.{/i}"
    m 1eub "{i}Time to call them!{/i}"
    m 1dua "{i}Hello there~{/i}"
    m "{i}Yeah, the room is open. You can all come over.{/i}"
    m 1sua "{i}Mhm... Of course.{/i}"
    # m "{i}I know my place.{/i}"
    # m "{i}Yes. I will do as I'm told.{/i}"
    # m "{i}I will do as {i}you{/i} say.{/i}"
    m 1eubsb "{i}Ahaha~ Please come over quick then!{/i}"
    m 1dubsa "..."
    m 1tubsa "{i}Hehe, did that excite you?{/i}"
    m 1hubsa "You hear me shuffling something. Maybe I'm applying some makeup and changing my outfit."
    m 1subsa "Time passes, there's a knock at the door."
    m 1tubsa "{i}What do you say? Shall I open it{/i}?"
    m 1tfbsa "{i}Well... it's too late to say otherwise.{/i}"
    m 1hubsa "I gently open the door~"
    m 1eubsb "And three others come inside of the room."
    m 4eubsa "{i}Hey, there! Welcome!{/i}"
    m "{i}Come in, come in.{/i}"
    m "{i}Take a seat.{/i}"
    m 4eubsb "{i}Do you need anything?{/i}"
    m "{i}A drink? Something to eat?{/i}"
    m "{i}I'm happy to get you whatever you want.{/i}"
    m 4tubsa "{i}You're the guests after all.{/i}"
    m "I offer them a tray of drinks."
    m 6mubsa "{i}How about we get things started?{i}"
    m 6tubsb "{i}Are you guys ready?{i}"
    m 5dubsa "I walk towards the middle of the room, and I start to strip, slowly."
    m "I flaunt my butt, grope my breasts."
    m "Hands wander and caress all over me."
    m 5kubsa "{i}Just lay back, and enjoy the show.{/i}"
    m 5tubsa "I spread my legs gently, and bend down a bit."
    m 5tkbsa "I put on some music... and begin twerking for them."
    # m "Hahaha~ can you hear it clap from there?"
    # m "Remember, whiteboi."
    # m "No touching yourself."
    m 5dkbsa "My panties drop to the floor."
    m 5dfbfa "I drop to my knees. "
    m 5kfbfa "You see my bubble butt squished by my bare feet."
    m 5subfb "{i}Stick your dicks in me and fill me with your cum.{/i}"
    m 5dubfb "{i}Please, I'm begging you.{/i}"
    m 5subfa "{i}I need to be filled up with your cum.{/i}"
    m 5tubfa "I open my mouth wide, inviting them, tempting them with my throat."
    m 5dkbfb "Three big, black meat rods being slapping my face.... ahnnn~"
    m 5subfa "{i}You all look so delicious.{/i}"
    m 5dubfa "I greedily shove one of them into my mouth, stroking the other two, before changing to the next one, then the next."
    m 5dfbfa "I give each shaft a kiss."
    m 5dkbfa "I lick and sniff their lowly drooping bull-like testicles."
    m 5dkbfb "The musk, the taste... my mind is in a haze."
    m 5tfbfa "But... you only see my dripping drool and my curling toes."
    m 5hubfa "After a while, I lay down on the bed and spread my legs."
    m "The three black studs get a good view of my pussy and ass."
    m 5subfa "{i}I can't wait to feel all of you inside of me.{/i}"
    m 5eubfb "{i}Please, please fuck me.{/i}"
    m "{i}Fuck me and fill me up with your cum.{/i}"
    m "{i}Please, I'm begging you.{/i}"
    m 5ekbfa "{i}I'm going to be a good little slut for you.{/i}"
    m "The studs all climb onto the bed, their sloppy cocks, dangling over my body."
    m 5skbfa "{i}I'm yours.{/i}"
    m "{i}I'm your little bitch.{/i}"
    m "{i}Please, fuck me.{/i}"
    m "{i}Use my body.{/i}"
    m "{i}Make me feel good.{/i}"
    m 5skbfb "{i}Please, I'm begging you.{/i}"
    m "{i}Please, please, please.{/i}"
    m 5dubfa "Then, without warning, the first stud enters me."
    m 6subfw "{i}F-fuck!{/i}"
    m "{i}Mmmmmm, yes, yes, yes.{/i}"
    m "{i}F-fuck!{/i}"
    m 5dkbfu "{i}Mmmmmm, yes, yes, yes.{/i}"
    m 5dkbfb "{i}Oh god, it feels so good.{/i}"
    m "{i}Ahhhh, fuck, it's so good.{/i}"
    m 5fubfa "{i}It's so big, and it's so thick, and it's filling me up so much.{/i}"
    m 5hubfb "{i}God, it's so good, I can't stop moaning.{/i}"
    m "{i}Mmmmm, god, yes, yes, yes, yes.{/i}"
    m "{i}Oh god, please, please, please, please.{/i}"
    m 5fkbfb "{i}Fuck me, please, fuck me, please.{/i}"
    m 5tfbfa "Underneath the bed, how does it feel? The shaking of the frame? Ahaha~"
    m 5dubfb "{i}God, please, I'm begging you.{/i}"
    m 5fkbfo "{i}I need your cum, I need your cum, I need your cum.{/i}"
    m "{i}Please, fill me up, please, fill me up, please.{/i}"
    m "{i}Please, I'm begging you.{/i}"
    m 5dkbfu "The second stud lubes up and begins fucking my ass."
    m 5skbfb "{i}Ahhhhhhh!{/i}"
    m "{i}Ahhh, fuck, it's so good, it hurts so goooood ahhhhhhh!{/i}"
    m 5tkbfu "The third stud enters my mouth."
    m 5dubfu "I'm getting fucked from all sides."
    m 5tubfu "At this point all you hear is your beloved girlfriend's muffled moans from underneath her bed."
    m 5dkbfb "My holes being stretched and filled with black seed."
    m "I can't stop cumming, and the black bulls keep on pumping load after load in all of my slutty, craving holes."
    m 5subfa "{i}MMmhhhhh!! MMMMMMmmpphhh!!!{/i}"
    m 5subfb "{i}MMMMHHHhhhh!!!{/i}"
    m 5skbfa "{i}Nghhh...{/i}"
    m 5hubfb "{i}Ahhhhh...{/i}"
    m 5hubfa "{i}Mmmmmm...{/i}"
    m 5dkbfb "{i}Oh ... mmmm, it feels so good...{/i}"
    m 5dkbfw "{i}Fuck, oh, it's so good, I can't stop cumming.{/i}"
    m 5dkbfb "{i}Ahhhnn~ , I can't stop cumming.{/i}"
    m "{i}Ahhh, fuck, it's so good.{/i}"
    m 5skbfb "{i}I love you all~{/i}"
    m 5skbfa"{i}I love your big black cocks~{/i}"
    m "{i}Thank you for your cum, Masters~{/i}"
    return "love"